#!/bin/sh

rm -f temporary* test-socket*

tests=0;
files=0;

failed=0;
failedfiles=0;
rv=0;

echo ";; running tests"

let "tests += 1";
./tests/server

echo ";; tests completed"

echo ";; ---- test summary ----"
echo ";; tests: ran $tests tests, $failed of them failed";

let "rv = $failed";

test "$rv" -eq "0"
